--- 
  - name: ensure SELinus is permissive
    selinux:
       policy: targeted
       state: permissive
  
  - name: nsure port is changed
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
       - httpd restarted 

 
  - name: ensure php is installed
    package:
       name: php
       state: present
  
  - name: ensure date is updated
    copy:
        dest: /var/www/html/date.php
        src: date.php
    notify:
       - httpd restarted 

...

       
